project:
  type: website
  preview:
    port: 3000
    browser: false
  output-dir: _docs

format:
  html:
    theme: cosmo
  ipynb: {}

website:
  sidebar:
    style: floating
    contents:
      - section: Explanations
        contents: explanations
  favicon: favicon.png
  navbar:
    left:
      - text: "Explanations"
        href: explanations/docs.ipynb
      - text: "Blog"
        href: blog/index.qmd

shortcodes:
  - colab.lua

nb_copy_dir: https://github.com/hamelsmu/quarto_nbcopy/blob/main/
